version: '3.8'

services:
  api:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=yt_user
      - POSTGRES_PASSWORD=yt_pass
      - POSTGRES_DB=yt_db

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80 # 5050 - local,  80 - in container
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecretPassword

volumes:
  postgres_data:
